### ISSUE TITLE
Cannot `run` due to nil device buffer

### ISSUE THREAD

**Issue by RyanScottLewis** [arirusso/midi-eye#3]
Code:
```ruby
def find_mpk(io)
  io.all.find { |device| device.name.downcase.strip.include?("mpk mini") }
end

input = find_mpk(UniMIDI::Input)

midi_listener = MIDIEye::Listener.new(input)
midi_listener.listen_for(:class => [MIDIMessage::NoteOn, MIDIMessage::NoteOff]) {|event| puts event[:message]}
midi_listener.run
```

Error:
```
Traceback (most recent call last):
        7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/midi-eye-0.3.10/lib/midi-eye/listener.rb:137:in `block in listen'
        6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/midi-eye-0.3.10/lib/midi-eye/listener.rb:126:in `listen_loop'
        5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/midi-eye-0.3.10/lib/midi-eye/listener.rb:126:in `loop'
        4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/midi-eye-0.3.10/lib/midi-eye/listener.rb:127:in `block in listen_loop'
        3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/midi-eye-0.3.10/lib/midi-eye/listener.rb:106:in `poll'
        2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/midi-eye-0.3.10/lib/midi-eye/listener.rb:106:in `each'
        1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/midi-eye-0.3.10/lib/midi-eye/listener.rb:107:in `block in poll'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/midi-eye-0.3.10/lib/midi-eye/source.rb:24:in `poll': undefined method `length' for nil:NilClass (NoMethodError)
```

Source:
https://github.com/arirusso/midi-eye/blob/dc9f2fac830d91321d4db7de7758246311f3c7be/lib/midi-eye/source.rb#L24

Note that changing the `input` to `input = UniMIDI::Input.first` allows the code to work just fine,.

**Comment by arirusso** [comment]
@RyanScottLewis 
Sorry for the slow reply here, getting back on track with these projects
the `first` method in unimidi, it automatically opens the device 
Not sure why I did that way back when? might want to change that

Nonetheless, for now I imagine your code will work if you do

```ruby
input = find_mpk(UniMIDI::Input)
input.open

midi_listener = MIDIEye::Listener.new(input)
midi_listener.listen_for(:class => [MIDIMessage::NoteOn, MIDIMessage::NoteOff]) {|event| puts event[:message]}
midi_listener.run
```

**Comment by RyanScottLewis** [comment]
It absolutely does, yes. I suppose it wasn't clear that devices had to be opened after using `first` for so long. Can close this one.

**Comment by arirusso** [comment]
Yeah, it's weird. Sorry for the confusion.  I need to do a freshen up that device API.  Once I get everything working smoothly with Ruby 3 that should be soon to follow
